/*
 * This Java source file was generated by the Gradle 'init' task.
 */

import org.junit.Test;

import javax.sql.rowset.CachedRowSet;
import javax.sql.rowset.RowSetFactory;
import javax.sql.rowset.RowSetProvider;
import java.sql.*;

public class JConnPoolTest {
	@Test
	public void testSomeLibraryMethod() throws ClassNotFoundException {
		JConnPool jConnPool = new JConnPool();
		String sql = "SELECT * FROM `city` WHERE `id` = 2";
		try {
			Connection conn = jConnPool.getConnection();
			PreparedStatement stmt = conn.prepareStatement(sql);
			ResultSet resultSet = stmt.executeQuery();
			RowSetFactory factory = RowSetProvider.newFactory();
			CachedRowSet cRst = factory.createCachedRowSet();
			cRst.populate(resultSet);
			while (cRst.next()) {
				System.out.println(cRst.getString(2));
			}
		} catch (SQLException e) {
			e.printStackTrace();
		}


	}

	public void connTest() throws ClassNotFoundException {
		String url = "jdbc:mysql://localhost:3306/keli_wincc?useSSL=true";
		Class.forName("com.mysql.cj.jdbc.Driver");
		String sql = "SELECT * FROM `city` WHERE `id` IN (?, ?, ?)";

		try (Connection conn = DriverManager.getConnection(url, "root", "root");
			 PreparedStatement stmt = conn.prepareStatement(sql)) {
			stmt.setObject(1, 1);
			stmt.setInt(2, 2);
			stmt.setInt(3, 3);
			ResultSet resultSet = stmt.executeQuery();

			RowSetFactory factory = RowSetProvider.newFactory();
			CachedRowSet cRst = factory.createCachedRowSet();
			cRst.populate(resultSet);
			while (cRst.next()) {
				System.out.println(cRst.getString(2));
			}
		} catch (SQLException e) {
			e.printStackTrace();
		}
	}

}
